# ========== GITHUB Aliases ==========
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcod='git checkout develop'
alias gcom='git checkout main'
alias gpl='git pull'
alias gph='git push'
alias gme='git merge'
alias gmed='git merge develop'
alias gmem='git merge main'
alias gcm='git commit'
alias gcmsg='git commit -am'
alias ga='git add'
alias gaa='git add .'
alias gcl='git clone'
alias gs='git status'
alias gst='git stash'
alias gstd='git stash drop'
alias gsta='git stash apply'
alias grh='git reset --hard'
alias grs='git reset --soft'

# ========== OTHER Aliases ==========
alias clr='clear'
alias zre='source ~/.zshrc'
