# ========== GITHUB Aliases ==========
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcod='git checkout develop'
alias gcom='git checkout main'
alias gcor='git checkout release'
alias gpl='git pull'
alias gph='git push'
alias gme='git merge'
alias gmed='git merge develop'
alias gmem='git merge main'
alias gmer='git merge release'
alias gcm='git commit'
alias gcmsg='git commit -am'
alias ga='git add'
alias gaa='git add .'
alias gcl='git clone'
alias gs='git status'
alias gst='git stash'
alias gstd='git stash drop'
alias gsta='git stash apply'
alias grh='git reset --hard'
alias grs='git reset --soft'
alias gcfm='git config --global user.email'

# ========== NPM Aliases ==========
alias ni='npm install'
alias ns='npm run start'
alias nw='npm run watch'
alias nd='npm run dev'
alias nb='npm run build'
alias nsd='npm run start:dev'
alias nsp='npm run start:prod'
alias nt='npm run test'

# ========== SSH Aliases ==========
alias ssha='ssh-add ~/.ssh/id_ed25519'
alias sshc='ssh -T git@github.com'
alias setupSsh='eval "$(ssh-agent -s)" && ssha && sshc'

# ========== Docker Aliases ==========
alias dcu='docker compose up'
alias dcud='docker compose up -d'
alias dcd='docker compose down'
alias dcr='docker compose restart'
alias dcs='docker compose stop'
alias dcsa='docker stop $(docker ps -a -q)'
alias dp='docker ps'

# ========== OTHER Aliases ==========
alias clr='clear'
alias co='code .'
alias zre='source ~/.zshrc'
